/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compare.triple;

import static java.util.stream.Collectors.toList;
import static org.junit.Assert.assertTrue;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import org.junit.Test;

public class AppTest {

  @Test
  public void 예1입력값제공_통과(){
    int[] alice = new int[]{5,6,7};
    int[] bob = new int[]{3,6,10};
    List<Integer> answer = new ArrayList<>();
    answer.add(0, 1);
    answer.add(1, 1);

    List<Integer> aliceList = Arrays.stream(alice).boxed().collect(toList());
    List<Integer> bobList = Arrays.stream(bob).boxed().collect(toList());

    Given_입력값과정답_When_compareTriplets_Then_Returend_True(aliceList, bobList, answer);
  }

  public void Given_입력값과정답_When_compareTriplets_Then_Returend_True(List<Integer> alice, List<Integer> bob, List<Integer> answer){
    List<Integer> result =App.compareTriplets(alice, bob);
    assertTrue(App.isListEqual(answer, result));
  }

  @Test
  public void Given_배열과리스트_When_같은지비교_Then_True반환(){
    // Given    
    List<Integer> list1 = new ArrayList<>();
    list1.add(1);
    list1.add(8);
    list1.add(7);
    List<Integer> list2 = new ArrayList<>();
    list2.add(1);
    list2.add(8);
    list2.add(7);
    
    // When
    boolean result = App.isListEqual(list1, list2);

    // Then
    assertTrue("리스트와 배열은 같아야합니다.", result);
  }
}
