/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

public class App {
    private static Calculator cal1 = null;
    private static Calculator cal2 = null;

    public static void main(String[] args) {
      cal1 = getCall("Addtion");
      System.out.println("10+20 = "+cal1.compute(10, 20));
      cal2 = getCall("Multiplication");
      System.out.println("3*9 = "+cal2.compute(3, 9));
    }

    public static Calculator getCall(String str) {
      if(str.equals("Addtion")) {
        return new Addition();
      }
      if(str.equals("Multiplication")){
        return new Multiplication();
      }
      throw new IllegalArgumentException("존재하지 않는 계산기 입니다.");
    }
}
