/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compare.triple;

import static java.util.stream.Collectors.joining;
import static java.util.stream.Collectors.toList;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

public class App {

    // Complete the compareTriplets function below.
    static List<Integer> compareTriplets(List<Integer> a, List<Integer> b) {
      List<Integer> result = new ArrayList<>();
      result.add(0, 0);
      result.add(1, 0);
      for(int i=0; i<a.size(); i++){
        if(a.get(i) > b.get(i)){
          result.set(0, result.get(0)+1);
        } else if(a.get(i) < b.get(i)){
          result.set(1, result.get(1)+1);
        }else{

        }
      }
      return result;
    }

    public static void main(String[] args) throws IOException {
        BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(System.in));
        BufferedWriter bufferedWriter = new BufferedWriter(new FileWriter(System.getenv("OUTPUT_PATH")));

        List<Integer> a = Stream.of(bufferedReader.readLine().replaceAll("\\s+$", "").split(" "))
            .map(Integer::parseInt)
            .collect(toList());

        List<Integer> b = Stream.of(bufferedReader.readLine().replaceAll("\\s+$", "").split(" "))
            .map(Integer::parseInt)
            .collect(toList());

        List<Integer> result = compareTriplets(a, b);

        bufferedWriter.write(
            result.stream()
                .map(Object::toString)
                .collect(joining(" "))
            + "\n"
        );

        bufferedReader.close();
        bufferedWriter.close();
    }

    public static boolean isListEqual(List<Integer> list1, List<Integer> list2){
      if(list1.size() != list2.size()) 
        throw new RuntimeException("엘리먼트 수가 같아야합니다.");
      
      for(int i=0; i<list1.size(); i++){
        if(!list1.get(i).equals(list2.get(i))){
          return false;
        }
      }
      return true;
    }
}
