/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test public void testReverser(){
        given_string_reverse_isEqual("Hello World!", "!dlroW olleH");
        given_string_reverse_isEqual("Hello World2!", "!2dlroW olleH");
        given_string_reverse_isEqual("apple", "elppa");

        given_string_reverse2_isEqual("hoop", "pooh");
        given_string_reverse2_isEqual("apple", "elppa");

        given_string_reverse2_isEqual("Hello World!", "!dlroW olleH");
        given_string_reverse2_isEqual("Hello World2!", "!2dlroW olleH");
    }

    private void given_string_reverse_isEqual(String input, String expected){
        String result = Reverser.reverse(input);
        assertEquals(expected, result);
    }
    private void given_string_reverse2_isEqual(String input, String expected){
        String result = Reverser.reverse2(input);
        assertEquals(expected, result);
    }
}
