/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package plus.minus;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        int[] arr = {-4, 3, -9, 0, 4, 1}; 
        double[] result = Solution.plusMinus(arr);
        for(double value : result){
            System.out.printf("%.6f\n", value);
        }
    }

}
